language: 
  java
jdk:
  - oraclejdk8
sudo: false
script: 
  - mvn clean -f ./Java/pom.xml
  - mvn compile -f ./Java/pom.xml
  #- mvn test -f ./Java/pom.xml -X
notifications:
  email: false

addons:
  apt:
    packages:
      - oracle-java8-installer