insert into StepSuggestion (content, type) values ('I click on "<buttonName>" button', 1);
insert into StepSuggestion (content, type) values ('I click on "<linkName>" link', 1);
insert into StepSuggestion (content, type) values ('I click on "<buttonName>" button from "<containerName>"', 1);
insert into StepSuggestion (content, type) values ('I click on "<linkName>" link from "<containerName>"', 1);
insert into StepSuggestion (content, type) values ('I check "<fieldName>"', 1);
insert into StepSuggestion (content, type) values ('I uncheck "<fieldName>"', 1);
insert into StepSuggestion (content, type) values ('checkbox "<fieldName>" is checked', 2);
insert into StepSuggestion (content, type) values ('checkbox "<fieldName>" is unchecked', 2);
insert into StepSuggestion (content, type) values ('for element "<fieldName>" I set attribute "<attributeName>" on "<attributeValue>"', 1);
insert into StepSuggestion (content, type) values ('element "<fieldName>" has attribute "<attributeName>" with value "<attributeValue>"', 2);
insert into StepSuggestion (content, type) values ('I submit form "<formName>" data "<json>"', 1);
insert into StepSuggestion (content, type) values ('I fill form "<formName>" data "<json>"', 1);
insert into StepSuggestion (content, type) values ('form "<formName>" contains data "<json>"', 2);
insert into StepSuggestion (content, type) values ('image "<fieldName>" has source "<source>"', 2);
insert into StepSuggestion (content, type) values ('image "<fieldName>" has alt "<alt>"', 2);
insert into StepSuggestion (content, type) values ('link "<linkName>" from "<containerName>" contains reference "<contains>"', 2);
insert into StepSuggestion (content, type) values ('link "<linkName>" from "<containerName>" match reference "<regex>"', 2);
insert into StepSuggestion (content, type) values ('I open "<pageName>"', 0);
insert into StepSuggestion (content, type) values ('I''m on "<pageName>"', 2);
insert into StepSuggestion (content, type) values ('I refresh page', 1);
insert into StepSuggestion (content, type) values ('I go back', 1);
insert into StepSuggestion (content, type) values ('I go forward', 1);
insert into StepSuggestion (content, type) values ('I check that page url match', 2);
insert into StepSuggestion (content, type) values ('I check that page url contains', 2);
insert into StepSuggestion (content, type) values ('On pagination "<paginationName>" I press next', 1);
insert into StepSuggestion (content, type) values ('On pagination "<paginationName>" I press previous', 1);
insert into StepSuggestion (content, type) values ('On pagination "<paginationName>" I select page number "<index>"', 1);
insert into StepSuggestion (content, type) values ('On pagination "<paginationName>" I go to last', 1);
insert into StepSuggestion (content, type) values ('On pagination "<paginationName>" I go to first', 1);
insert into StepSuggestion (content, type) values ('I find "<findString>"', 1);
insert into StepSuggestion (content, type) values ('I input to "<filedName>" lines "<lines>"', 1);
insert into StepSuggestion (content, type) values ('I input to "<filedName>" new line "<newLine>"', 1);
insert into StepSuggestion (content, type) values ('field "<filedName>" contains "<contains>"', 2);
insert into StepSuggestion (content, type) values ('I input to "<filedName>" new input "<newInput>"', 1);
insert into StepSuggestion (content, type) values ('I fill "<fieldName>" textfield with "<data>"', 0);
insert into StepSuggestion (content, type) values ('I fill field "<fieldName>" by text "<text>"', 3);
insert into StepSuggestion (content, type) values ('text "<fieldName>" contains "<contains>"', 2);
insert into StepSuggestion (content, type) values ('label "<fieldName>" contains "<contains>"', 2);
insert into StepSuggestion (content, type) values ('link "<fieldName>" contains "<contains>"', 2);
insert into StepSuggestion (content, type) values ('button "<fieldName>" contains "<contains>"', 2);
insert into StepSuggestion (content, type) values ('text "<fieldName>" match "<regex>"', 2);
insert into StepSuggestion (content, type) values ('label "<fieldName>" match "<regex>"', 2);
insert into StepSuggestion (content, type) values ('link "<fieldName>" match "<regex>"', 2);
insert into StepSuggestion (content, type) values ('button "<fieldName>" match "<regex>"', 2);
insert into StepSuggestion (content, type) values ('text "<linkName>" from "<containerName>" contains "<contains>"', 2);
insert into StepSuggestion (content, type) values ('label "<linkName>" from "<containerName>" contains "<contains>"', 2);
insert into StepSuggestion (content, type) values ('link "<linkName>" from "<containerName>" contains "<contains>"', 2);
insert into StepSuggestion (content, type) values ('button "<linkName>" from "<containerName>" contains "<contains>"', 2);
insert into StepSuggestion (content, type) values ('text "<linkName>" from "<containerName>" match  "<regex>"', 2);
insert into StepSuggestion (content, type) values ('label "<linkName>" from "<containerName>" match  "<regex>"', 2);
insert into StepSuggestion (content, type) values ('link "<linkName>" from "<containerName>" match  "<regex>"', 2);
insert into StepSuggestion (content, type) values ('button "<linkName>" from "<containerName>" match  "<regex>"', 2);