insert into StepSuggestion (id, content, type) values (1, 'I click on "<buttonName>" button', 1);
insert into StepSuggestion (id, content, type) values (2, 'I click on "<linkName>" link', 1);
insert into StepSuggestion (id, content, type) values (3, 'I click on "<buttonName>" button from "<containerName>"', 1);
insert into StepSuggestion (id, content, type) values (4, 'I click on "<linkName>" link from "<containerName>"', 1);
insert into StepSuggestion (id, content, type) values (5, 'I check "<fieldName>"', 1);
insert into StepSuggestion (id, content, type) values (6, 'I uncheck "<fieldName>"', 1);
insert into StepSuggestion (id, content, type) values (7, 'checkbox "<fieldName>" is checked', 2);
insert into StepSuggestion (id, content, type) values (8, 'checkbox "<fieldName>" is unchecked', 2);
insert into StepSuggestion (id, content, type) values (9, 'for element "<fieldName>" I set attribute "<attributeName>" on "<attributeValue>"', 1);
insert into StepSuggestion (id, content, type) values (10, 'element "<fieldName>" has attribute "<attributeName>" with value "<attributeValue>"', 2);
insert into StepSuggestion (id, content, type) values (11, 'I submit form "<formName>" data "<json>"', 1);
insert into StepSuggestion (id, content, type) values (12, 'I fill form "<formName>" data "<json>"', 1);
insert into StepSuggestion (id, content, type) values (13, 'form "<formName>" contains data "<json>"', 2);
insert into StepSuggestion (id, content, type) values (14, 'image "<fieldName>" has source "<source>"', 2);
insert into StepSuggestion (id, content, type) values (15, 'image "<fieldName>" has alt "<alt>"', 2);
insert into StepSuggestion (id, content, type) values (16, 'link "<linkName>" from "<containerName>" contains reference "<contains>"', 2);
insert into StepSuggestion (id, content, type) values (17, 'link "<linkName>" from "<containerName>" match reference "<regex>"', 2);
insert into StepSuggestion (id, content, type) values (18, 'I open "<pageName>"', 0);
insert into StepSuggestion (id, content, type) values (19, 'I''m on "<pageName>"', 2);
insert into StepSuggestion (id, content, type) values (20, 'I refresh page', 1);
insert into StepSuggestion (id, content, type) values (21, 'I go back', 1);
insert into StepSuggestion (id, content, type) values (22, 'I go forward', 1);
insert into StepSuggestion (id, content, type) values (23, 'I check that page url match', 2);
insert into StepSuggestion (id, content, type) values (24, 'I check that page url contains', 2);
insert into StepSuggestion (id, content, type) values (25, 'On pagination "<paginationName>" I press next', 1);
insert into StepSuggestion (id, content, type) values (26, 'On pagination "<paginationName>" I press previous', 1);
insert into StepSuggestion (id, content, type) values (27, 'On pagination "<paginationName>" I select page number "<index>"', 1);
insert into StepSuggestion (id, content, type) values (28, 'On pagination "<paginationName>" I go to last', 1);
insert into StepSuggestion (id, content, type) values (29, 'On pagination "<paginationName>" I go to first', 1);
insert into StepSuggestion (id, content, type) values (30, 'I find "<findString>"', 1);
insert into StepSuggestion (id, content, type) values (31, 'I input to "<filedName>" lines "<lines>"', 1);
insert into StepSuggestion (id, content, type) values (32, 'I input to "<filedName>" new line "<newLine>"', 1);
insert into StepSuggestion (id, content, type) values (33, 'field "<filedName>" contains "<contains>"', 2);
insert into StepSuggestion (id, content, type) values (34, 'I input to "<filedName>" new input "<newInput>"', 1);
insert into StepSuggestion (id, content, type) values (35, 'I fill "<fieldName>" textfield with "<data>"', 0);
insert into StepSuggestion (id, content, type) values (36, 'I fill field "<fieldName>" by text "<text>"', 3);
insert into StepSuggestion (id, content, type) values (37, 'text "<fieldName>" contains "<contains>"', 2);
insert into StepSuggestion (id, content, type) values (38, 'label "<fieldName>" contains "<contains>"', 2);
insert into StepSuggestion (id, content, type) values (39, 'link "<fieldName>" contains "<contains>"', 2);
insert into StepSuggestion (id, content, type) values (40, 'button "<fieldName>" contains "<contains>"', 2);
insert into StepSuggestion (id, content, type) values (41, 'text "<fieldName>" match "<regex>"', 2);
insert into StepSuggestion (id, content, type) values (42, 'label "<fieldName>" match "<regex>"', 2);
insert into StepSuggestion (id, content, type) values (43, 'link "<fieldName>" match "<regex>"', 2);
insert into StepSuggestion (id, content, type) values (44, 'button "<fieldName>" match "<regex>"', 2);
insert into StepSuggestion (id, content, type) values (45, 'text "<linkName>" from "<containerName>" contains "<contains>"', 2);
insert into StepSuggestion (id, content, type) values (46, 'label "<linkName>" from "<containerName>" contains "<contains>"', 2);
insert into StepSuggestion (id, content, type) values (47, 'link "<linkName>" from "<containerName>" contains "<contains>"', 2);
insert into StepSuggestion (id, content, type) values (48, 'button "<linkName>" from "<containerName>" contains "<contains>"', 2);
insert into StepSuggestion (id, content, type) values (49, 'text "<linkName>" from "<containerName>" match  "<regex>"', 2);
insert into StepSuggestion (id, content, type) values (50, 'label "<linkName>" from "<containerName>" match  "<regex>"', 2);
insert into StepSuggestion (id, content, type) values (51, 'link "<linkName>" from "<containerName>" match  "<regex>"', 2);
insert into StepSuggestion (id, content, type) values (52, 'button "<linkName>" from "<containerName>" match  "<regex>"', 2);